USE [master]
GO

/****** Object:  Database [QLyDoanHoi]    Script Date: 12/06/2016 21:53:20 ******/
CREATE DATABASE [QLyDoanHoi] ON  PRIMARY 
( NAME = N'QLyDoanHoi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\QLyDoanHoi.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QLyDoanHoi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\QLyDoanHoi_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QLyDoanHoi] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLyDoanHoi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLyDoanHoi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [QLyDoanHoi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLyDoanHoi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLyDoanHoi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLyDoanHoi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLyDoanHoi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLyDoanHoi] SET  READ_WRITE 
GO

ALTER DATABASE [QLyDoanHoi] SET RECOVERY FULL 
GO

ALTER DATABASE [QLyDoanHoi] SET  MULTI_USER 
GO

ALTER DATABASE [QLyDoanHoi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLyDoanHoi] SET DB_CHAINING OFF 
GO


